apiVersion: v1
kind: Service
metadata:
  namespace: rider-guide
  name: frontend-svc
spec:
 type: ClusterIP
 ports:
   - port: 80 #service port
     targetPort: 80 #pod port
 selector:
    app: frontend
