apiVersion: v1
kind: Service
metadata:
  namespace: rider-guide
  name: mongodb-svc
spec:
 type: ClusterIP
 ports:
   - port: 27017 #service port
     targetPort: 27017 #pod port
 selector:
    app: mongodb
